
#include <stdio.h>
#include <unistd.h>

#define CHUNK_LENGTH 16
#define CHUNK_WIDTH 16
#define CHUNK_HEIGHT 16
#define CHUNK_SIZE (CHUNK_LENGTH * CHUNK_WIDTH * CHUNK_HEIGHT)

#define PRINT_RES ((CHUNK_LENGTH+CHUNK_HEIGHT) * (CHUNK_WIDTH+CHUNK_HEIGHT))
#define PRINT_RES2 (CHUNK_LENGTH*CHUNK_WIDTH)